# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/api/*" 
  to = "https://api.clashofclans.com/:splat" 
  status = 301
  force = true
  headers = {X-From = "Netlify"}
  signed = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjY3OGIxYmRlLTUzOGEtNGI0Ni1iMjY0LTQzYTllZTRkNTQ2MiIsImlhdCI6MTY5MDM4NzMyMCwic3ViIjoiZGV2ZWxvcGVyLzczZGY3Yjk0LThkNzktZWM0YS1iMjE0LWRlN2NiZmE2OTkxNiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3OC4yMzUuMTg4LjI1NCIsIjM0LjE0MS41NS4yNTAiXSwidHlwZSI6ImNsaWVudCJ9XX0.bs21JsEt0U7yRD_x4WGTJDPPTluH-j1vJpOlEbiUhjeC2_R84Jth5-1Wlj9pbrrHSjHPlA7UlIpZPJFKbo7G_w"
[[headers]]
  for = "/api/*" 
  [headers.values]
  Access-Control-Allow-Origin = "*"
  